/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { FamilyCreateNestedManyWithoutUsersInput } from "./FamilyCreateNestedManyWithoutUsersInput";
import { ValidateNested, IsOptional, IsString, IsJSON } from "class-validator";
import { Type } from "class-transformer";
import { RecipeCreateNestedManyWithoutUsersInput } from "./RecipeCreateNestedManyWithoutUsersInput";
import { RatingCreateNestedManyWithoutUsersInput } from "./RatingCreateNestedManyWithoutUsersInput";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: () => FamilyCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => FamilyCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => FamilyCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  families?: FamilyCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => RecipeCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => RecipeCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => RecipeCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  favoriteRecipes?: RecipeCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: false,
    type: () => RecipeCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => RecipeCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => RecipeCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  postedRecipes?: RecipeCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => RatingCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => RatingCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => RatingCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  ratings?: RatingCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
  })
  @IsJSON()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;
}
export { UserCreateInput };
