/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  ValidateNested,
  IsOptional,
  IsString,
  IsJSON,
} from "class-validator";
import { Type } from "class-transformer";
import { Family } from "../../family/base/Family";
import { Recipe } from "../../recipe/base/Recipe";
import { Rating } from "../../rating/base/Rating";
import { GraphQLJSON } from "graphql-type-json";
import { JsonValue } from "type-fest";

@ObjectType()
class User {
  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: () => [Family],
  })
  @ValidateNested()
  @Type(() => Family)
  @IsOptional()
  families?: Array<Family>;

  @ApiProperty({
    required: false,
    type: () => [Recipe],
  })
  @ValidateNested()
  @Type(() => Recipe)
  @IsOptional()
  favoriteRecipes?: Array<Recipe>;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName!: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName!: string | null;

  @ApiProperty({
    required: false,
    type: () => Family,
  })
  @ValidateNested()
  @Type(() => Family)
  @IsOptional()
  ownFamily?: Family | null;

  @ApiProperty({
    required: false,
    type: () => [Recipe],
  })
  @ValidateNested()
  @Type(() => Recipe)
  @IsOptional()
  postedRecipes?: Array<Recipe>;

  @ApiProperty({
    required: false,
    type: () => [Rating],
  })
  @ValidateNested()
  @Type(() => Rating)
  @IsOptional()
  ratings?: Array<Rating>;

  @ApiProperty({
    required: true,
  })
  @IsJSON()
  @Field(() => GraphQLJSON)
  roles!: JsonValue;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;
}

export { User };
