/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Family, User, Recipe, SmartTag } from "@prisma/client";

export class FamilyServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.FamilyFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.FamilyFindManyArgs>
  ): Promise<number> {
    return this.prisma.family.count(args);
  }

  async findMany<T extends Prisma.FamilyFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.FamilyFindManyArgs>
  ): Promise<Family[]> {
    return this.prisma.family.findMany(args);
  }
  async findOne<T extends Prisma.FamilyFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.FamilyFindUniqueArgs>
  ): Promise<Family | null> {
    return this.prisma.family.findUnique(args);
  }
  async create<T extends Prisma.FamilyCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.FamilyCreateArgs>
  ): Promise<Family> {
    return this.prisma.family.create<T>(args);
  }
  async update<T extends Prisma.FamilyUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.FamilyUpdateArgs>
  ): Promise<Family> {
    return this.prisma.family.update<T>(args);
  }
  async delete<T extends Prisma.FamilyDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.FamilyDeleteArgs>
  ): Promise<Family> {
    return this.prisma.family.delete(args);
  }

  async findMember(
    parentId: string,
    args: Prisma.UserFindManyArgs
  ): Promise<User[]> {
    return this.prisma.family
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .member(args);
  }

  async findOwnUsers(
    parentId: string,
    args: Prisma.UserFindManyArgs
  ): Promise<User[]> {
    return this.prisma.family
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .ownUsers(args);
  }

  async findRecipes(
    parentId: string,
    args: Prisma.RecipeFindManyArgs
  ): Promise<Recipe[]> {
    return this.prisma.family
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .recipes(args);
  }

  async findSmartTags(
    parentId: string,
    args: Prisma.SmartTagFindManyArgs
  ): Promise<SmartTag[]> {
    return this.prisma.family
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .smartTags(args);
  }
}
